title: One HECJ of a Journey
author: James C.E. Howell
email: jcehowell2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will describe my journey from my start in IT until where I am now and the next steps that I plan to take.

theme: minima
# social links
twitter_username: hecj1
github_username:  hecj1

show_excerpts: true # set to false to remove excerpts on the homepage
